### ISSUE TITLE
Gateway up or down

### ISSUE THREAD

**Issue by bcomsugi** [computourist/RFM69-MQTT-client#10]
Hi, how do you know if the gateway is up or down?
i can't ping the gateway, and the gateway seem didnt implement reconnect if the connection(LAN) is disconnected

**Comment by rickskibinski** [comment]
I am using an Mqtt client (lens) in chrome browser to send status request messages to the gateway. The documentation on the gateway covers how to do that.

**Comment by computourist** [comment]
You should be able to ping the LAN-connection of your gateway. If this is not the case, do you have a link-indicator on your ethernet port ? Is your MAC-adrress (as defined in the sketch) unique in your network?
If the ethernet port is up, the MQTT LED will indicate connection to you broker. In debug mode, a connection message will be present on the serial port. A MQTT client (I use myMQTT on Android) can be used to detect messages. (subscribe to home/rfm_gw/# )
