### ISSUE TITLE
harinazov interrupt disable  w5100.h

### ISSUE THREAD

**Issue by consolacion** [computourist/RFM69-MQTT-client#16]
Sadly the jcw source that harinazov refers to for interupt disabling is dead. just as the link to Arduino.cc. So all i know is that the W5100.h file needs to be amended with:
#else
inline static void initSS() { DDRB |= _BV(2); };
inline static void setSS() { cli(); PORTB &= ~_BV(2); };
inline static void resetSS() { PORTB |= _BV(2); sei(); };
#endif
Am I correct it replaces this section:
 inline static void initSS()    { DDRB  |=  _BV(2); };
 inline static void setSS()     { PORTB &= ~_BV(2); };
 inline static void resetSS()   { PORTB |=  _BV(2); };

**Comment by computourist** [comment]
Have a look at: http://homeautomation.proboards.com/post/166
Changes are around line 343 in w5100.h

**Comment by consolacion** [comment]
ah, yes, that seems to be the sectionI guessed it was. Tnx
