### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by flatsiedatsie** [computourist/RFM69-MQTT-client#18]
The readme is a bit cryptic. Can this be used to
- Switch RF433 wall plugs? Can it learn their codes? Does it store their codes, or pass them along?
- Listen to RF433 signals from sensors, and pass along their data? Like temperature sensors for example?
- Could this be used with Domoticz?
- All one has to do is connect the RFM69 to the Raspberry Pi's pins?

**Comment by computourist** [comment]
RTFM
