### ISSUE TITLE
Node can't reach gateway, is a relay node a solution?

### ISSUE THREAD

**Issue by Gizzbert** [computourist/RFM69-MQTT-client#19]
Hi,
I have a node sitting in a faraday cage of sorts, therefore it can't reach the gateway. Is a relay node a solution for that, will it forward all the messages it gets?

cheers

**Comment by computourist** [comment]
Hi Gizzbert,
there are several solutions for this. A relay node is certainly possible, but you would have to write the code for it. This should not be too difficult when combining already existing code. 

Other possible solutions would be:
- place a second gateway inside the cage. Operating a multitide of gateways within a single network is no problem, if only the MQTT parameters are unique for each gateway.
- place the antenna for the RFM96 outside the cage, using a coaxial feed.
- place the node outside the cage, and connect the sensors and actuators using wired connections.
- use an ESP-based node. It operates using Wifi. This option would only work if Wifi is available within the cage.

Hope this helps....

Computourist

**Comment by Gizzbert** [comment]
thanks for the quick reply! 

I hoped the "Relay end node" would have this purpose (https://github.com/computourist/RFM69-MQTT-client/tree/master/Relay%20end%20node) but it seems like I have to tinker on. As I can't get any wiring inside, I will probably opt for a node forwarding messages. (which right now is a bit over my head, lets see)
