### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by djash40** [computourist/RFM69-MQTT-client#7]
Hi, I am new to programming and please excuse my ignorance in asking these questions. I have  2  moteinos and I have a working sketch that I would like to connect to MQTT. One as a node and one as the gateway connected to a Raspberry Pi for network communications. So far I have the end node communicating with the gateway and printing out to the serial port on the gateway . Now I would like to take the serial port and communicate over MQTT.  This is where I'm stuck on making a choice. I have looked at many options Ruby Python and of course your code to create the serial to mqtt connection and I'm not sure where to go next. While looking at your code it seems it requires an Ethernet shield on the moteino.  Is this correct?  Or can I use my Raspberry Pi's  Mac address in the gateway sketch?  Please advise.

**Comment by computourist** [comment]
Which sketch have you implemented ? The gateway described here connects to fixed ethernet only. A serial output is provided, but only for informational debugging messages. 
A Raspberry Pi is not needed for this gateway (although it could be used to run Mosquitto)
