### ISSUE TITLE
nRF24l01+ support

### ISSUE THREAD

**Issue by petrolej** [computourist/RFM69-MQTT-client#9]
Hi,

great job. I am about to set your code in my home. This is exactly what I was looking for. I needed an arduino based gateway which would be only a bridge between a wireless node and ethernet and acts as a subscriber for a distant MQTT broker. 

I wonder whether the code could be altered to work with nRF24l01+ which is much cheaper.

Keep doing well.

Petr

**Comment by computourist** [comment]
Hi,
Thanx for the kind words..

With respect to using nRF24l01: It works in the 2.4 GHz band, so its range and abiliy to penetrate walls is less that the RFM-Module that works in a lower frequency band. On Top: the RFM-69 module gives you encryption, making communications safe. 
For me these are arguments against the use of nRF24l01...

Regards,
Computourist
